# Generated by Django 4.0.4 on 2022-04-30 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecrpg', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bannedplayer',
            old_name='by',
            new_name='adminName',
        ),
    ]
