# Generated by Django 4.0.4 on 2022-04-28 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecrpg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managementteam',
            name='lvl',
            field=models.IntegerField(),
        ),
    ]
