# Generated by Django 4.0.4 on 2022-05-04 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecrpg', '0002_remove_wikicategory_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='wikicategory',
            name='img',
            field=models.FilePathField(default='demo.jpg', path='/img'),
        ),
    ]
