# Generated by Django 4.0.4 on 2022-04-28 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecrpg', '0002_alter_managementteam_lvl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wikicategory',
            name='img',
            field=models.FilePathField(default='/img/icon', path='/img'),
        ),
    ]
