# Generated by Django 4.0.4 on 2022-05-04 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecrpg', '0004_alter_wikicategory_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wikicategory',
            name='img',
            field=models.FilePathField(default='/icons/<django.db.models.fields.CharField>', path='/svg'),
        ),
    ]
