# Generated by Django 4.0.4 on 2022-05-04 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecrpg', '0010_wikicategory_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wikicategory',
            name='img',
            field=models.FilePathField(default='/icons/demo.svg', path='svg/'),
        ),
    ]
