# Generated by Django 4.0.4 on 2022-05-04 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecrpg', '0011_alter_wikicategory_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wikicategory',
            name='img',
        ),
    ]
