<?php 
/***************************************************** 
* Title : 		footer.
* Intention :	unite all footer info in one document
* Created : 	10.04-17 
* Important notice:		 
*******************************************************/
?>

			<footer>
				<P class="rctcr"> 
					Copy rights &#169 all rights reserved by <a href="rctechnolegy.com" title="RC Technolegy">RC Technolegy LTD</a>
				</P>
				<p> 
				Stay tuned for our updates
				</p> 
				<ul>
					<li>
						<a href="https://www.facebook.com">
							<i class="fa fa-facebook-square" style="font-size:2em;" title="Facebook"> </i>
						</a>	
					</li>
					<li>
						<a href="https://www.instagram.com">
							<i class="fa fa-instagram" style="font-size:2em;" title="Instagram"></i>
						</a>
					</li>
					<li>
						<a href="https://www.github.com">
							<i class="fa fa-github-square" style="font-size: 2em" title="github"></i>
						</a>
					</li>
					<li>
						<a href="mailto:krigjo25@gmail.com ">
							<i class="fas fa-mail-bulk" style="font-size: 2em" title="Subscribe"></i>
						</a>
					</li>
				</ul>
			</footer>
	</body>
</html>