# Generated by Django 4.0.4 on 2022-04-17 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('krigjo25', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PythonProjects',
            new_name='MyProjects',
        ),
    ]
